spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  cloud:
    stream:
      kafka:
        binder:
          brokers: pkc-gq2xn.asia-northeast3.gcp.confluent.cloud:9092
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required username='VBLBCZGY6YKNW3S5' password='FZgPC6j1eAtRxxM8A7g7sfg2vR/qtj2gdhN+QwkyH2l+9h+2/Eq8soJE72wheTCZ';
              mechanism: PLAIN
            client:
              dns:
                lookup: use_all_dns_ips

          required-acks: all
          auto-create-topics: false

        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result

      bindings:
        send-out-0:
          destination: payment
          group: payment-service

#    function:
#      definition: send;wallet;ledger

logging:
  level:
    org:
      springframework:
        web: DEBUG
        r2dbc: DEBUG
        transaction: DEBUG

PSP:
  toss:
    url: https://api.tosspayments.com
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

management:
  endpoints:
    web:
      exposure:
        include: bindings